first commit
ntretyakov1/calculated-age pull request #1
Opened 2023-03-22 12:29 UTC by ntretyakov1

2023-03-22 12:58 UTC, KushchevR requested changes
В целом нужно почистить коммит от тех файлов, которые не нужны

2023-03-22 12:58 UTC, KushchevR commented on README.MD
> +        - logo_dp.png 174px x 109px;
Не вижу описание задачи, что необходимо выполнить?! Изменить!

2023-03-22 12:58 UTC, KushchevR commented on api.js
> +}
Слишком много не используемого, оставить только те методы, которые нужны

2023-03-22 12:58 UTC, KushchevR commented on index.js
> +const idFieldAge = "377623";
нейминг в соответствии с правилами переписать (смотри константы)

2023-03-22 12:58 UTC, KushchevR commented on index.js
> +api.getAccessToken().then(() => {
Избавиться от цепочки. Вынести эндпоинт и внутри уже после срабатывания тригера вызывать логику

2023-03-22 12:58 UTC, KushchevR commented on index.js
> +		const obj = {
Нейминг. Что за obj?! Непонятно

2023-03-22 12:58 UTC, KushchevR commented on utils.js
> +};
Так же почисти. Оставить только то что используешь

2023-03-22 12:58 UTC, KushchevR commented on widget/manifest.json
> +    "salesbot_designer"
Почитай доку "АМО" и оставь только там где реально используется виджет

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +const { getFieldValue, makeField } = require("./utils");
Переписать на import

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +};
вынести в utils

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +const ID_FIELD_AGE = "377623";
создать файл consts.js и там хранить все константы

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +	const contact = req.body.contacts.add[0];
Избавиться от индекса
const [contact] = req.body.contacts.add;

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +		return;
помести res.send в return

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +	if (Math.sign(age) === -1) {
Мне кажется if(age < 0) проще и понятнее

2023-03-23 07:17 UTC, mzudin-reon commented on index.js
> +	api.updateContacts(contactForUpdate).then(() => {
api.updateContacts(contactForUpdate).then( () => res.send("OK") );

2023-03-28 12:30 UTC, merged